In [1]:
import numpy as np
import pandas as pd

pd.pandas.set_option('display.max_columns',None)
pd.pandas.set_option('display.max_rows',None)

In [2]:
data_nutrition_food = pd.read_csv('Daily_Nutrion_Food.csv')
data_nutrition_req = pd.read_csv('Daily_Nutrion_Required.csv')

In [3]:
data_nutrition_food.head()

,Food,Serving Size,calories,total_fat,cholesterol,saturated_fat,sodium,vitamin_a,vitamin_b12,vitamin_b6,vitamin_c,caffeine,water,zinc,sugars,carbohydrate,protein,fiber,calcium,iron,magnesium
0,Egg,100 g,322,27 g,9.6 g,1085 mg,48.00 mg,0.4326 mg,0.00195 mg,0.350 mg,0.0 mg,0.00 mg,87.57 g,2.30 mg,0.56 g,3.59 g,13 g,0.0 g,50.00 mg,1.2 mg,10.00 mg
1,Milk,100 g,42,4.5 g,5 g,600 mg,44.00 mg,0.0141 mg,0.0005 mg,0.0 mg,0.0 mg,0.00 mg,90.00 g,0.4 mg,5 g,5 g,3.4 g,0.0 g,125.00 mg,0.00 mg,11.00 mg
2,Bread,100 g,293,3.3 g,0.001 g,700 mg,621.00 mg,0.0012 mg,0.00007 mg,0.096 mg,0.3 mg,0.00 mg,30.00 g,1.52 mg,6 g,41 g,13 g,4.0 g,260.00 mg,3.60 mg,25.00 mg
3,Potato,100 g,77,0.1 g,0.00 g,0.00 mg,6.00 mg,0.0006 mg,0.00 mg,0.239 mg,19.7 mg,0.00 mg,80.00 g,1.00 mg,0.8 g,17 g,2 g,2.0 g,12.00 mg,0.80 mg,23.00 mg
4,Carrots,100 g,35,0.2 g,0.00 g,0.00 mg,302.00 mg,0.51099 mg,0.00 mg,0.153 mg,3.6 mg,0.00 mg,90.17 g,0.24 mg,3.45 g,8.22 g,0.76 g,3.3 g,35.00 mg,0.53 mg,11.00 mg

In [4]:
data_nutrition_req.head()

,Gender,Weight,calories,total_fat,cholesterol,saturated_fat,sodium,vitamin_a,vitamin_b12,vitamin_b6,vitamin_c,caffeine,water,zinc,sugars,carbohydrate,protein,fiber,calcium,iron,magnesium
0,Male,75,2500,30 g,300 mg,30000 g,2300 mg,0.9 mg,2.4 mg,1.3 mg,90 mg,400 mg,3700 g,11 mg,36 mg,347 g,weight * 0.8,34 g,900 mg,8 mg,410 mg
1,Female,60,2200,25 g,300 mg,18000 g,2300 mg,0.7 mg,2.4 mg,1.3 mg,75 mg,400 mg,3000 g,8 mg,24 mg,347 g,weight * 0.8,25 g,900 mg,18 mg,315 mg

In [5]:
df = data_nutrition_food.iloc[: , 3:]

In [6]:
df.head()

,total_fat,cholesterol,saturated_fat,sodium,vitamin_a,vitamin_b12,vitamin_b6,vitamin_c,caffeine,water,zinc,sugars,carbohydrate,protein,fiber,calcium,iron,magnesium
0,27 g,9.6 g,1085 mg,48.00 mg,0.4326 mg,0.00195 mg,0.350 mg,0.0 mg,0.00 mg,87.57 g,2.30 mg,0.56 g,3.59 g,13 g,0.0 g,50.00 mg,1.2 mg,10.00 mg
1,4.5 g,5 g,600 mg,44.00 mg,0.0141 mg,0.0005 mg,0.0 mg,0.0 mg,0.00 mg,90.00 g,0.4 mg,5 g,5 g,3.4 g,0.0 g,125.00 mg,0.00 mg,11.00 mg
2,3.3 g,0.001 g,700 mg,621.00 mg,0.0012 mg,0.00007 mg,0.096 mg,0.3 mg,0.00 mg,30.00 g,1.52 mg,6 g,41 g,13 g,4.0 g,260.00 mg,3.60 mg,25.00 mg
3,0.1 g,0.00 g,0.00 mg,6.00 mg,0.0006 mg,0.00 mg,0.239 mg,19.7 mg,0.00 mg,80.00 g,1.00 mg,0.8 g,17 g,2 g,2.0 g,12.00 mg,0.80 mg,23.00 mg
4,0.2 g,0.00 g,0.00 mg,302.00 mg,0.51099 mg,0.00 mg,0.153 mg,3.6 mg,0.00 mg,90.17 g,0.24 mg,3.45 g,8.22 g,0.76 g,3.3 g,35.00 mg,0.53 mg,11.00 mg

In [7]:
df_req = data_nutrition_req.iloc[: , 3:]
df_req

,total_fat,cholesterol,saturated_fat,sodium,vitamin_a,vitamin_b12,vitamin_b6,vitamin_c,caffeine,water,zinc,sugars,carbohydrate,protein,fiber,calcium,iron,magnesium
0,30 g,300 mg,30000 g,2300 mg,0.9 mg,2.4 mg,1.3 mg,90 mg,400 mg,3700 g,11 mg,36 mg,347 g,weight * 0.8,34 g,900 mg,8 mg,410 mg
1,25 g,300 mg,18000 g,2300 mg,0.7 mg,2.4 mg,1.3 mg,75 mg,400 mg,3000 g,8 mg,24 mg,347 g,weight * 0.8,25 g,900 mg,18 mg,315 mg

In [8]:
def data_split(df):
    df_new = pd.DataFrame()

    for feature in df.columns:
        new = df[feature].str.split(" ", n = 1, expand = True)
        new = new.iloc[:,0:1]
        new.columns = [feature]
        df_new = pd.concat([df_new,new],axis=1)
    return df_new

In [9]:
data_nutrition_food_new = data_split(df)

In [10]:
data_nutrition_food_new.head()

,total_fat,cholesterol,saturated_fat,sodium,vitamin_a,vitamin_b12,vitamin_b6,vitamin_c,caffeine,water,zinc,sugars,carbohydrate,protein,fiber,calcium,iron,magnesium
0,27,9.6,1085,48.00,0.4326,0.00195,0.350,0.0,0.00,87.57,2.30,0.56,3.59,13,0.0,50.00,1.2,10.00
1,4.5,5,600,44.00,0.0141,0.0005,0.0,0.0,0.00,90.00,0.4,5,5,3.4,0.0,125.00,0.00,11.00
2,3.3,0.001,700,621.00,0.0012,0.00007,0.096,0.3,0.00,30.00,1.52,6,41,13,4.0,260.00,3.60,25.00
3,0.1,0.00,0.00,6.00,0.0006,0.00,0.239,19.7,0.00,80.00,1.00,0.8,17,2,2.0,12.00,0.80,23.00
4,0.2,0.00,0.00,302.00,0.51099,0.00,0.153,3.6,0.00,90.17,0.24,3.45,8.22,0.76,3.3,35.00,0.53,11.00

In [11]:
data_nutrition_req_new = data_split(df_req)

In [12]:
data_nutrition_req_new.head()

,total_fat,cholesterol,saturated_fat,sodium,vitamin_a,vitamin_b12,vitamin_b6,vitamin_c,caffeine,water,zinc,sugars,carbohydrate,protein,fiber,calcium,iron,magnesium
0,30,300,30000,2300,0.9,2.4,1.3,90,400,3700,11,36,347,weight,34,900,8,410
1,25,300,18000,2300,0.7,2.4,1.3,75,400,3000,8,24,347,weight,25,900,18,315

In [13]:
a = data_nutrition_food[['Food','Serving Size','calories']]
data_nutrition_food_new = pd.concat([a,data_nutrition_food_new],axis=1)
data_nutrition_food_new.head()

,Food,Serving Size,calories,total_fat,cholesterol,saturated_fat,sodium,vitamin_a,vitamin_b12,vitamin_b6,vitamin_c,caffeine,water,zinc,sugars,carbohydrate,protein,fiber,calcium,iron,magnesium
0,Egg,100 g,322,27,9.6,1085,48.00,0.4326,0.00195,0.350,0.0,0.00,87.57,2.30,0.56,3.59,13,0.0,50.00,1.2,10.00
1,Milk,100 g,42,4.5,5,600,44.00,0.0141,0.0005,0.0,0.0,0.00,90.00,0.4,5,5,3.4,0.0,125.00,0.00,11.00
2,Bread,100 g,293,3.3,0.001,700,621.00,0.0012,0.00007,0.096,0.3,0.00,30.00,1.52,6,41,13,4.0,260.00,3.60,25.00
3,Potato,100 g,77,0.1,0.00,0.00,6.00,0.0006,0.00,0.239,19.7,0.00,80.00,1.00,0.8,17,2,2.0,12.00,0.80,23.00
4,Carrots,100 g,35,0.2,0.00,0.00,302.00,0.51099,0.00,0.153,3.6,0.00,90.17,0.24,3.45,8.22,0.76,3.3,35.00,0.53,11.00

In [14]:
def enter_your_details_and_food_intake():
    items = int(input('How many food items you consume ? : '))
    
    gender = input("Gender {(Male/male) or (Female/female)}: ")
    if((gender=='Male') or (gender == 'male')):
        gender=0
    elif ((gender=='Female') or (gender == 'female')):
        gender=1
        
    body_weight = float(input('What is your body weight ? : '))
    foods = []
    serving_size = []
    for i in range(0,items):
        food_name = (input('Enter the food name : '))
        food_serving_size = float(input('Enter amount of food intake (gm): '))
        serving_size.append(food_serving_size)
        foods.append(food_name)
    return foods, serving_size, items, body_weight, gender

In [15]:
food, serving, items, body_weight, gender = enter_your_details_and_food_intake()

How many food items you consume ? : 5
Gender {(Male/male) or (Female/female)}: Male
What is your body weight ? : 76
Enter the food name : Egg
Enter amount of food intake (gm): 70.3
Enter the food name : Milk
Enter amount of food intake (gm): 147.3
Enter the food name : Green Pea
Enter amount of food intake (gm): 35.7
Enter the food name : Potato
Enter amount of food intake (gm): 100
Enter the food name : Carrots
Enter amount of food intake (gm): 0

In [16]:
food

['Egg', 'Milk', 'Green Pea', 'Potato', 'Carrots']

In [17]:
serving

[70.3, 147.3, 35.7, 100.0, 0.0]

In [18]:
items

5

In [19]:
body_weight

76.0

In [20]:
gender

0

In [21]:
total_food = len(food)
data_food_consumed = pd.DataFrame()

for j in range(0, total_food):
    new = data_nutrition_food_new[data_nutrition_food_new['Food'] == food[j]]
    data_food_consumed = pd.concat([data_food_consumed,new],axis=0)
    
data_food_consumed.head()

,Food,Serving Size,calories,total_fat,cholesterol,saturated_fat,sodium,vitamin_a,vitamin_b12,vitamin_b6,vitamin_c,caffeine,water,zinc,sugars,carbohydrate,protein,fiber,calcium,iron,magnesium
0,Egg,100 g,322,27,9.6,1085,48.00,0.4326,0.00195,0.350,0.0,0.00,87.57,2.30,0.56,3.59,13,0.0,50.00,1.2,10.00
1,Milk,100 g,42,4.5,5,600,44.00,0.0141,0.0005,0.0,0.0,0.00,90.00,0.4,5,5,3.4,0.0,125.00,0.00,11.00
14,Green Pea,100 g,81,0.4,0.00,100,5.00,0.2295,0.00,0.200,40.00,0.00,66.80,1.19,6.00,14.00,5.00,5.00,25.00,1.50,33.00
3,Potato,100 g,77,0.1,0.00,0.00,6.00,0.0006,0.00,0.239,19.7,0.00,80.00,1.00,0.8,17,2,2.0,12.00,0.80,23.00
4,Carrots,100 g,35,0.2,0.00,0.00,302.00,0.51099,0.00,0.153,3.6,0.00,90.17,0.24,3.45,8.22,0.76,3.3,35.00,0.53,11.00

In [22]:
def data_type_convsersion_to_float(df):
    df_new = pd.DataFrame()

    for feature in df.columns:
        new = df[feature].astype(float)
        df_new = pd.concat([df_new,new],axis=1)
    
    return df_new

In [23]:
df_food_consumed = data_food_consumed.iloc[: , 3:]
df_food_consumed = data_type_convsersion_to_float(df_food_consumed)
df_food_consumed

,total_fat,cholesterol,saturated_fat,sodium,vitamin_a,vitamin_b12,vitamin_b6,vitamin_c,caffeine,water,zinc,sugars,carbohydrate,protein,fiber,calcium,iron,magnesium
0,27.0,9.6,1085.0,48.0,0.43260,0.00195,0.350,0.0,0.0,87.57,2.30,0.56,3.59,13.00,0.0,50.0,1.20,10.0
1,4.5,5.0,600.0,44.0,0.01410,0.00050,0.000,0.0,0.0,90.00,0.40,5.00,5.00,3.40,0.0,125.0,0.00,11.0
14,0.4,0.0,100.0,5.0,0.22950,0.00000,0.200,40.0,0.0,66.80,1.19,6.00,14.00,5.00,5.0,25.0,1.50,33.0
3,0.1,0.0,0.0,6.0,0.00060,0.00000,0.239,19.7,0.0,80.00,1.00,0.80,17.00,2.00,2.0,12.0,0.80,23.0
4,0.2,0.0,0.0,302.0,0.51099,0.00000,0.153,3.6,0.0,90.17,0.24,3.45,8.22,0.76,3.3,35.0,0.53,11.0

In [24]:
data_nutrition_req = data_nutrition_req_new.iloc[[gender]]
type(data_nutrition_req)

pandas.core.frame.DataFrame

In [25]:
data_nutrition_req = data_nutrition_req.replace({'protein': 'weight'}, body_weight*0.8)

In [26]:
data_nutrition_req

,total_fat,cholesterol,saturated_fat,sodium,vitamin_a,vitamin_b12,vitamin_b6,vitamin_c,caffeine,water,zinc,sugars,carbohydrate,protein,fiber,calcium,iron,magnesium
0,30,300,30000,2300,0.9,2.4,1.3,90,400,3700,11,36,347,60.8,34,900,8,410

In [27]:
def data_object_to_float(df):
    df_new = pd.DataFrame()

    for feature in df.columns:
        new = df[feature].astype(float)
        df_new = pd.concat([df_new,new],axis=1)
    
    return df_new

In [28]:
df_food_consumed = data_food_consumed.iloc[: , 3:]
df_food_consumed = data_object_to_float(df_food_consumed)
df_food_consumed

,total_fat,cholesterol,saturated_fat,sodium,vitamin_a,vitamin_b12,vitamin_b6,vitamin_c,caffeine,water,zinc,sugars,carbohydrate,protein,fiber,calcium,iron,magnesium
0,27.0,9.6,1085.0,48.0,0.43260,0.00195,0.350,0.0,0.0,87.57,2.30,0.56,3.59,13.00,0.0,50.0,1.20,10.0
1,4.5,5.0,600.0,44.0,0.01410,0.00050,0.000,0.0,0.0,90.00,0.40,5.00,5.00,3.40,0.0,125.0,0.00,11.0
14,0.4,0.0,100.0,5.0,0.22950,0.00000,0.200,40.0,0.0,66.80,1.19,6.00,14.00,5.00,5.0,25.0,1.50,33.0
3,0.1,0.0,0.0,6.0,0.00060,0.00000,0.239,19.7,0.0,80.00,1.00,0.80,17.00,2.00,2.0,12.0,0.80,23.0
4,0.2,0.0,0.0,302.0,0.51099,0.00000,0.153,3.6,0.0,90.17,0.24,3.45,8.22,0.76,3.3,35.0,0.53,11.0

In [29]:
df_nutrition_req = data_object_to_float(data_nutrition_req)
df_nutrition_req

,total_fat,cholesterol,saturated_fat,sodium,vitamin_a,vitamin_b12,vitamin_b6,vitamin_c,caffeine,water,zinc,sugars,carbohydrate,protein,fiber,calcium,iron,magnesium
0,30.0,300.0,30000.0,2300.0,0.9,2.4,1.3,90.0,400.0,3700.0,11.0,36.0,347.0,60.8,34.0,900.0,8.0,410.0

In [30]:
print('Food consumed data type info:-')
print(df_food_consumed.info())

print()
print()

print('Nutrition required data type info:-')
print(df_nutrition_req.info())

Food consumed data type info:-
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 4
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   total_fat      5 non-null      float64
 1   cholesterol    5 non-null      float64
 2   saturated_fat  5 non-null      float64
 3   sodium         5 non-null      float64
 4   vitamin_a      5 non-null      float64
 5   vitamin_b12    5 non-null      float64
 6   vitamin_b6     5 non-null      float64
 7   vitamin_c      5 non-null      float64
 8   caffeine       5 non-null      float64
 9   water          5 non-null      float64
 10  zinc           5 non-null      float64
 11  sugars         5 non-null      float64
 12  carbohydrate   5 non-null      float64
 13  protein        5 non-null      float64
 14  fiber          5 non-null      float64
 15  calcium        5 non-null      float64
 16  iron           5 non-null      float64
 17  magnesium      5 non-null      float64
dtypes: float64(18)
memory usage: 760.0+ bytes
None


Nutrition required data type info:-
<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, 0 to 0
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   total_fat      1 non-null      float64
 1   cholesterol    1 non-null      float64
 2   saturated_fat  1 non-null      float64
 3   sodium         1 non-null      float64
 4   vitamin_a      1 non-null      float64
 5   vitamin_b12    1 non-null      float64
 6   vitamin_b6     1 non-null      float64
 7   vitamin_c      1 non-null      float64
 8   caffeine       1 non-null      float64
 9   water          1 non-null      float64
 10  zinc           1 non-null      float64
 11  sugars         1 non-null      float64
 12  carbohydrate   1 non-null      float64
 13  protein        1 non-null      float64
 14  fiber          1 non-null      float64
 15  calcium        1 non-null      float64
 16  iron           1 non-null      float64
 17  magnesium      1 non-null      float64
dtypes: float64(18)
memory usage: 152.0+ bytes
None

In [31]:
# sum over the column axis.
df_food_consumed['total_fat'].sum()

32.2

In [32]:
serving[0]

70.3

In [33]:
df_food_consumed[0:1]

,total_fat,cholesterol,saturated_fat,sodium,vitamin_a,vitamin_b12,vitamin_b6,vitamin_c,caffeine,water,zinc,sugars,carbohydrate,protein,fiber,calcium,iron,magnesium
0,27.0,9.6,1085.0,48.0,0.4326,0.00195,0.35,0.0,0.0,87.57,2.3,0.56,3.59,13.0,0.0,50.0,1.2,10.0

In [34]:
new = df_food_consumed.iloc[[1]]*(serving[0]/100)
new

,total_fat,cholesterol,saturated_fat,sodium,vitamin_a,vitamin_b12,vitamin_b6,vitamin_c,caffeine,water,zinc,sugars,carbohydrate,protein,fiber,calcium,iron,magnesium
1,3.1635,3.515,421.8,30.932,0.009912,0.000351,0.0,0.0,0.0,63.27,0.2812,3.515,3.515,2.3902,0.0,87.875,0.0,7.733

In [35]:
def nutrition_consumed(df):
    df_new = pd.DataFrame()

    for i in range(0, items):
        new = df_food_consumed.iloc[[i]]*(serving[i]/100)
        df_new = pd.concat([df_new,new],axis=0)
    
    return df_new

In [36]:
data_food_consumed_final = nutrition_consumed(df_food_consumed)
data_food_consumed_final

,total_fat,cholesterol,saturated_fat,sodium,vitamin_a,vitamin_b12,vitamin_b6,vitamin_c,caffeine,water,zinc,sugars,carbohydrate,protein,fiber,calcium,iron,magnesium
0,18.9810,6.7488,762.755,33.744,0.304118,0.001371,0.24605,0.00,0.0,61.56171,1.61690,0.39368,2.52377,9.1390,0.000,35.150,0.8436,7.030
1,6.6285,7.3650,883.800,64.812,0.020769,0.000737,0.00000,0.00,0.0,132.57000,0.58920,7.36500,7.36500,5.0082,0.000,184.125,0.0000,16.203
14,0.1428,0.0000,35.700,1.785,0.081932,0.000000,0.07140,14.28,0.0,23.84760,0.42483,2.14200,4.99800,1.7850,1.785,8.925,0.5355,11.781
3,0.1000,0.0000,0.000,6.000,0.000600,0.000000,0.23900,19.70,0.0,80.00000,1.00000,0.80000,17.00000,2.0000,2.000,12.000,0.8000,23.000
4,0.0000,0.0000,0.000,0.000,0.000000,0.000000,0.00000,0.00,0.0,0.00000,0.00000,0.00000,0.00000,0.0000,0.000,0.000,0.0000,0.000

In [37]:
def sum_of_nutrition_consumed(df):
    df_new = pd.DataFrame()
    
    for feature in df.columns:
        new[feature] = df[feature].sum()
        df_new = pd.concat([df_new,new[feature]],axis=1)
    
    return df_new

In [38]:
data_nutrition_consumed_final = sum_of_nutrition_consumed(data_food_consumed_final)
data_nutrition_consumed_final

,total_fat,cholesterol,saturated_fat,sodium,vitamin_a,vitamin_b12,vitamin_b6,vitamin_c,caffeine,water,zinc,sugars,carbohydrate,protein,fiber,calcium,iron,magnesium
1,25.8523,14.1138,1682.255,106.341,0.407419,0.002107,0.55645,33.98,0.0,297.97931,3.63093,10.70068,31.88677,17.9322,3.785,240.2,2.1791,58.014

In [39]:
print(data_nutrition_consumed_final.shape)
print(df_nutrition_req.shape)

(1, 18)
(1, 18)

In [40]:
data_final_check = pd.concat([data_nutrition_consumed_final,df_nutrition_req]).transpose()
data_final_check.columns = ['data_nutrition_consumed_final','df_nutrition_req']
data_final_check

               data_nutrition_consumed_final  df_nutrition_req
total_fat                          25.852300              30.0
cholesterol                        14.113800             300.0
saturated_fat                    1682.255000           30000.0
sodium                            106.341000            2300.0
vitamin_a                           0.407419               0.9
vitamin_b12                         0.002107               2.4
vitamin_b6                          0.556450               1.3
vitamin_c                          33.980000              90.0
caffeine                            0.000000             400.0
water                             297.979310            3700.0
zinc                                3.630930              11.0
sugars                             10.700680              36.0
carbohydrate                       31.886770             347.0
protein                            17.932200              60.8
fiber                               3.785000              34.0
calcium                           240.200000             900.0
iron                                2.179100               8.0
magnesium                          58.014000             410.0

In [41]:
data_final_check.loc[(data_final_check['data_nutrition_consumed_final'] > data_final_check['df_nutrition_req']),
                      'Requirement'] = 'Consuming Sufficiently'

data_final_check.loc[(data_final_check['data_nutrition_consumed_final'] == data_final_check['df_nutrition_req']),
                      'Requirement'] = 'Consuming Perfectly'
                       
data_final_check.loc[(data_final_check['data_nutrition_consumed_final'] < data_final_check['df_nutrition_req']),
                      'Requirement'] = 'Consuming Insufficiently'

data_final_check

,data_nutrition_consumed_final,df_nutrition_req,Requirement
total_fat,25.852300,30.0,Consuming Insufficiently
cholesterol,14.113800,300.0,Consuming Insufficiently
saturated_fat,1682.255000,30000.0,Consuming Insufficiently
sodium,106.341000,2300.0,Consuming Insufficiently
vitamin_a,0.407419,0.9,Consuming Insufficiently
vitamin_b12,0.002107,2.4,Consuming Insufficiently
vitamin_b6,0.556450,1.3,Consuming Insufficiently
vitamin_c,33.980000,90.0,Consuming Insufficiently
caffeine,0.000000,400.0,Consuming Insufficiently
water,297.979310,3700.0,Consuming Insufficiently
zinc,3.630930,11.0,Consuming Insufficiently
sugars,10.700680,36.0,Consuming Insufficiently
carbohydrate,31.886770,347.0,Consuming Insufficiently
protein,17.932200,60.8,Consuming Insufficiently
fiber,3.785000,34.0,Consuming Insufficiently
calcium,240.200000,900.0,Consuming Insufficiently
iron,2.179100,8.0,Consuming Insufficiently
magnesium,58.014000,410.0,Consuming Insufficiently

In [44]:
data_final_check['data_nutrition_consumed_final'][17]

58.013999999999996